const ArtCollectionsCollection = [
    {
        // documentTitle: 'Tardigrades - AI art collection by Rodrigo Barraza',
        documentTitle: 'Tardigrades, - AI art by Rodrigo Barraza',
        // documentTitle: 'Monochrome Photography - Rodrigo barraza, Vancouver Photographer1234',
        documentKeywords: 'tardigrade, tardigrada, ai art, rodrigo barraza, artificial intelligence, machine learning, clip-guided diffusion, disco diffusion',
        documentDescription: 'Tardigrades is a series of aritificial intelligence generated images. A visual exploration into the nature of CLIP-guided diffusion.',
        title: 'Tardigrades',
        type: 'ai',
        medium: 'CLIP-guided diffusion, AI generated',
        year: 2022,
        path: 'tardigrades',
        ekphrasis: 'Once men turned their thinking over to machines in the hope that this would set them free. But that only permitted other men with machines to enslave them.',
        description: 'This series of aritificial intelligence generated images is an exploration into the nature of CLIP-guided diffusion and the collection of neural network architectures that build upon it. Along side each piece is an ekphrasis, which has been composed by the use of GPT-3 autoregressive language models. Tardigrades (Tardigrada) were chosen as the subject to render.',
        works: [
            {
                path: 'tardigrade-001',
                imagePath: 'tardigrade-001',
                title: 'Diamond Tardigrade No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                ekphrasis: 'This species of Tardigrada has been known to carry around a home made out of transparent crystals. Found in a variety of habitats, the usually prefer to live in moist environments.',
                year: '2022',
            },
            {
                path: 'tardigrade-002',
                imagePath: 'tardigrade-002',
                title: 'Pink Velvet Tardigrade No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                description: '',
                year: '2022',
            },
            {
                path: 'tardigrade-003',
                imagePath: 'tardigrade-003',
                title: 'Carbon Black Tardigrade No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                year: '2022',
            },
            {
                path: 'tardigrade-004',
                imagePath: 'tardigrade-004',
                title: 'Astrophysical Tardigrade No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                year: '2022',
            },
            {
                path: 'tardigrade-005',
                imagePath: 'tardigrade-005',
                title: 'Anodic Tardigrade No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                year: '2022',
            },
            {
                path: 'tardigrade-006',
                imagePath: 'tardigrade-006',
                title: 'Anodic Tardigrade No. 002',
                medium: 'CLIP-guided diffusion, AI generated',
                year: '2022',
            },
        ]
    },
    {
        documentTitle: 'Dreamwork - Photography by Rodrigo Barraza',
        documentKeywords: 'dreamwork, vancouver, photography, rodrigo barraza, film, medium format, hasselblad, analog, multiple exposure, slide, traditional, fine art',
        documentDescription: 'Dreamwork is a collection of medium format photographs, surrounding the intangible subjects of memory, emotion and dreams.',
        title: 'Dreamwork',
        type: 'photography',
        medium: 'medium format color reversal film',
        year: 2010,
        path: 'dreamwork',
        ekphrasis: 'Dreamwork; memories, emotions, dreams, and their intangibility. Memories develop as information is encoded, stored and retried. Emotions are brought on through assossiations. Dreams are a succession of concepts occuring involuntarily in the mind curing certain stages of sleep.',
        description: 'A collection of multiple exposure photographs, shot on medium format slide film. Dreamwork is a visual exploration on the fragility of memories, emotional responses, experience of dreams, and the intertwinedness these three topics share.',
        orientation: 'square',
        works: [
            {
                path: 'rodrigo-barraza-dreamwork-the-beach',
                imagePath: 'rodrigo-barraza-dreamwork-the-beach',
                title: 'The Beach',
                medium: 'medium format color reversal film',
                ekphrasis: 'Amalgamated memories of the beach, from a time that might have never happened. A feeling of jamais vu.',
                description: 'Amalgamated memories of the beach, from a time that might have never happened. A feeling of jamais vu.',
                year: 2010,
            },
            {
                path: 'rodrigo-barraza-dreamwork-the-yard',
                imagePath: 'rodrigo-barraza-dreamwork-the-yard',
                title: 'The Yard',
                medium: 'medium format color reversal film',
                ekphrasis: 'Seven very similar looking corners of a fenced-out backyard. A feeling of déjà vu.',
                description: 'Am',
                year: 2010,
            },
            {
                path: 'rodrigo-barraza-dreamwork-the-park',
                imagePath: 'rodrigo-barraza-dreamwork-the-park',
                title: 'The Park',
                medium: 'medium format color reversal film',
                ekphrasis: '',
                description: '',
                year: 2010,
            },
            {
                path: 'rodrigo-barraza-2010-120-fuji-provia-100f-star-shell',
                imagePath: 'rodrigo-barraza-2010-120-fuji-provia-100f-star-shell',
                title: 'The Gas Station',
                medium: 'medium format color reversal film',
                ekphrasis: 'A long time ago, time went by so slowly, waiting for the bus.',
                description: 'Shot on Fuji Provia 100f, enlarged on silver-halide paper.',
                year: 2010,
            },
            // {
            //     path: 'dreamworks-004',
            //     imagePath: 'dreamworks-004',
            //     title: 'Dreamworks No. 004',
            //     medium: 'medium format slide film',
            //     ekphrasis: 'When one is so tired that far away objects feel close while nearby objects can be seen distance away. Like vertigo that goes sideways.',
            //     description: 'Amalgamated memories of the beach, from a time that might have never happened. A feeling of jamais vu.',
            //     year: 2011,
            // },
        ]
    },
    {
        documentTitle: 'Cops - Photography by Rodrigo Barraza',
        documentKeywords: 'cops, police officer, vancouver, photography, rodrigo barraza, black and white, film, 35mm',
        documentDescription: 'xxx',
        title: 'Cops',
        type: 'photography',
        medium: '35mm black-and-white film',
        year: 2010,
        path: 'cops',
        description: '',
        orientation: 'vertical',
        works: [
            {
                path: 'cops-001',
                imagePath: 'cops-001',
                title: 'Serve',
                medium: '35 mm black-and-white film',
                description: '',
                year: 2010,
            },
            {
                path: 'cops-002',
                imagePath: 'cops-002',
                title: 'Protect',
                medium: '35 mm black-and-white film',
                description: '',
                year: 2010,
            },
            {
                path: 'cops-003',
                imagePath: 'cops-003',
                title: 'Justice',
                medium: '35 mm black-and-white film',
                description: '',
                year: 2010,
            },
        ]
    },
    {
        documentTitle: 'Strolls - Photography by Rodrigo Barraza',
        documentKeywords: 'strolls, vancouver, photography, rodrigo barraza, film',
        documentDescription: 'xxx',
        title: 'Strolls',
        type: 'photography',
        medium: 'medium format color film',
        year: 2010,
        path: 'strolls',
        ekphrasis: 'xxx',
        description: 'This is a collection of photographs shot on black-and-white medium format slide film.',
        orientation: 'square',
        works: [
            {
                path: '2010-120-fuji-provia-100f-perisids',
                imagePath: '2010-120-fuji-provia-100f-perisids',
                title: '23.5 degrees',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
            {
                path: '120_provia_beams',
                imagePath: '120_provia_beams',
                title: 'Gleam',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
            {
                path: '2010-120-fuji-provia-100f-building',
                imagePath: '2010-120-fuji-provia-100f-building',
                title: 'Nook',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
            {
                path: 'runs-001',
                imagePath: 'runs-001',
                title: 'Wicker Chair',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
            {
                path: '2010-120-fuji-velvia-100-bench',
                imagePath: '2010-120-fuji-velvia-100-bench',
                title: 'Metal Bench',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
            {
                path: '120_provia_lightShowGood',
                imagePath: '120_provia_lightShowGood',
                title: 'Lasers',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
            // {
            //     path: 'skeleton',
            //     imagePath: 'skeleton',
            //     title: 'Mr. Skeletal',
            //     medium: 'medium format color reversal film',
            //     description: '',
            //     year: 2010,
            // },
        ]
    },
    {
        documentTitle: 'Angela - Photography by Rodrigo Barraza',
        documentKeywords: 'angela, vancouver, photography, rodrigo barraza, film',
        documentDescription: 'xxx',
        title: 'Angela',
        type: 'photography',
        medium: 'medium format film',
        year: 2010,
        path: 'angela',
        ekphrasis: 'xxx',
        description: 'xxx',
        orientation: 'square',
        works: [
            {
                path: '2010-120-ilford-delta-400-angela-portrait-001',
                imagePath: '2010-120-ilford-delta-400-angela-portrait-001',
                title: 'Angela No.1',
                medium: 'medium format black-and-white film',
                year: 2010,
            },
            {
                path: '2010-120-ilford-delta-400-angela-portrait-002',
                imagePath: '2010-120-ilford-delta-400-angela-portrait-002',
                title: 'Angela No.2',
                medium: 'medium format black-and-white film',
                year: 2010,
            },
            {
                path: '2009-120-ilford-delta-400-angela-full-body-001',
                imagePath: '2009-120-ilford-delta-400-angela-full-body-001',
                title: 'Angela No.3',
                medium: 'medium format black-and-white film',
                year: 2010,
            },
            {
                path: '2010-120-fuji-velvia-100-angelaBody',
                imagePath: '2010-120-fuji-velvia-100-angelaBody',
                title: 'Angela No.4',
                medium: 'medium format color negative film',
                year: 2010,
            },
            {
                path: 'fashion-medium-0003',
                imagePath: 'fashion-medium-0003',
                title: 'Angela No.5',
                medium: 'medium format color negative film',
                year: 2010,
            },
            {
                path: '2010-120-fuji-pro-160s-angela',
                imagePath: '2010-120-fuji-pro-160s-angela',
                title: 'Angela No.6',
                medium: 'medium format color reversal film',
                year: 2010,
            },
        ]
    },
    {
        documentTitle: 'Walks - Photography by Rodrigo Barraza',
        documentKeywords: 'walks, vancouver, photography, rodrigo barraza, film',
        documentDescription: 'xxx',
        title: 'Walks',
        type: 'photography',
        medium: 'medium format black-and-white film',
        year: 2010,
        path: 'walks',
        ekphrasis: 'There is a certain feeling that comes on when walking around with a camera. It is a lonely but comfortable warmth.',
        description: 'This is a collection of photographs shot on black-and-white medium format slide film.',
        orientation: 'square',
        works: [
            {
                path: 'walks-001',
                imagePath: 'walks-001',
                title: 'Shower',
                medium: 'medium format black-and-white film',
                description: 'Overlooking the container ships, breakbulk carriers and tankers from English Bay, Vancouver.',
                year: 2010,
            },
            {
                path: 'walks-002',
                imagePath: 'walks-002',
                title: 'Beam',
                medium: 'medium format black-and-white film',
                description: 'Spotlights at Sunset Beach for the Vancouver Winter Olympics.',
                year: 2010,
            },
            {
                path: 'walks-003',
                imagePath: 'walks-003',
                title: 'We',
                medium: 'medium format black-and-white film',
                description: 'WE, a sculpture by Jaume Plensa.',
                year: 2010,
            },
            {
                path: 'walks-004',
                imagePath: 'walks-004',
                title: 'Robson and Granville',
                medium: 'medium format black-and-white film',
                description: 'Two weeks of chaos, as people flood the streets in preperation for the Vancouver Winter Olympics.',
                year: 2010,
            },
            {
                path: '2010-120-fuji-acros-100-backalley-river',
                imagePath: '2010-120-fuji-acros-100-backalley-river',
                title: 'Alley River',
                medium: 'medium format black-and-white film',
                description: '',
                year: 2010,
            },
            {
                path: 'walks-005',
                imagePath: 'walks-005',
                title: 'Dirty, Dangerous and Demeaning',
                medium: 'medium format black-and-white film',
                description: 'Also known as the 3Ds; Dirty, Dangerous and Demanding is a North American neologism derived from the Japanese expression: kitanai, kiken, kitsui[1] (汚い "dirty", 危険 "dangerous", きつい "demanding"), and refers to certain kinds of labor often performed by unionized blue-collar workers.',
                year: 2010,
            },

            
            // {
            //     path: '2010-120-fuji-provia-100f-perisids',
            //     imagePath: '2010-120-fuji-provia-100f-perisids',
            //     title: '23.5 degrees',
            //     medium: 'medium format black-and-white film',
            //     description: '',
            //     year: 2010,
            // },
            // {
            //     path: '120_provia_beams',
            //     imagePath: '120_provia_beams',
            //     title: 'Gleam',
            //     medium: 'medium format black-and-white film',
            //     description: '',
            //     year: 2010,
            // },
            // {
            //     path: 'runs-000',
            //     imagePath: 'runs-000',
            //     title: 'Nook',
            //     medium: 'medium format black-and-white film',
            //     description: '',
            //     year: 2010,
            // },
            // {
            //     path: 'runs-001',
            //     imagePath: 'runs-001',
            //     title: 'Wicker and Wood',
            //     medium: 'medium format black-and-white film',
            //     description: '',
            //     year: 2010,
            // },
            // {
            //     path: 'skeleton',
            //     imagePath: 'skeleton',
            //     title: 'Mr. Skeletal',
            //     medium: 'medium format black-and-white film',
            //     description: '',
            //     year: 2010,
            // },
        ]
    },
    {
        documentTitle: 'Crystal Landscapes - AI Art by Rodrigo Barraza',
        documentKeywords: 'crystal landscapes, ai art, rodrigo barraza',
        documentDescription: 'xxx',
        title: 'Crystal Landscapes',
        type: 'ai',
        medium: 'CLIP-guided diffusion, AI generated',
        year: 'Ongoing',
        path: 'crystal-landscapes',
        description: 'A collection of ongoing AI art pieces, CLIP-guided diffusion.',
        orientation: 'vertical',
        works: [
            {
                path: 'crystal-skies-001',
                imagePath: 'crystal-skies-001',
                title: 'Crystal Skies No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                year: 2022,
            },
            {
                path: 'crystal-beach-001',
                imagePath: 'crystal-beach-001',
                title: 'Crystal Beach No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                description: '',
                year: 2022,
            },
            {
                path: 'crystal-beach-002',
                imagePath: 'crystal-beach-002',
                title: 'Crystal Beach No. 002',
                medium: 'CLIP-guided diffusion, AI generated',
                description: '',
                year: 2022,
            },
            // {
            //     path: 'crystal-landscapes-004',
            //     imagePath: 'crystal-landscapes-004',
            //     title: 'Crystal Beach No. 002',
            //     medium: 'CLIP-guided diffusion, AI generated',
            //     year: 2022,
            // },
            // {
            //     path: 'crystal-peak-001',
            //     imagePath: 'crystal-peak-001',
            //     title: 'Crystal Peak No. 002',
            //     medium: 'CLIP-guided diffusion, AI generated',
            //     year: 2022,
            // },
            {
                path: 'crystal-ridge-001',
                imagePath: 'crystal-ridge-001',
                title: 'Crystal Ridge No. 002',
                medium: 'CLIP-guided diffusion, AI generated',
                year: 2022,
            },
            {
                path: 'crystal-seashore-001',
                imagePath: 'crystal-seashore-001',
                title: 'Crystal Seashore No. 002',
                medium: 'CLIP-guided diffusion, AI generated',
                year: 2022,
            },
            // {
            //     path: 'crystal-city-001',
            //     imagePath: 'crystal-city-001',
            //     title: 'Crystal City No. 001',
            //     medium: 'CLIP-guided diffusion, AI generated',
            //     year: 2022,
            // },
        ]
    },
    {
        documentTitle: 'Persons - Photography by Rodrigo Barraza',
        documentKeywords: 'persons, vancouver, photography, rodrigo barraza, film',
        documentDescription: 'xxx',
        title: 'Persons',
        type: 'photography',
        medium: 'medium format color negative film',
        year: 2011,
        path: 'persons',
        orientation: 'square',
        description: '',
        works: [
            // {
            //     path: 'persons-001',
            //     imagePath: 'persons-001',
            //     title: 'The Model',
            //     medium: 'medium format color negative film',
            //     description: '',
            //     year: 2011,
            // },
            {
                path: 'persons-004',
                imagePath: 'persons-004',
                title: 'The Landlord',
                medium: 'medium format color negative film',
                year: 2011,
            },
            {
                path: 'persons-002',
                imagePath: 'persons-002',
                title: 'The Writer',
                medium: 'medium format color negative film',
                description: '',
                year: 2011,
            },
            {
                path: 'persons-003',
                imagePath: 'persons-003',
                title: 'The Art Teacher',
                medium: 'medium format color negative film',
                year: 2011,
            },
            {
                path: 'persons-006',
                imagePath: 'persons-006',
                title: 'The Vagabonds',
                medium: 'medium format color negative film',
                year: 2011,
            },
            {
                path: 'persons-007',
                imagePath: 'persons-007',
                title: 'The Actor',
                medium: 'medium format color negative film',
                year: 2011,
            },
            {
                path: 'persons-008',
                imagePath: 'persons-008',
                title: 'The Courier',
                medium: 'medium format color negative film',
                year: 2011,
            },
            {
                path: 'persons-009',
                imagePath: 'persons-009',
                title: 'The Clerk',
                medium: 'medium format color negative film',
                year: 2011,
            },
            // {
            //     path: 'persons-010',
            //     imagePath: 'persons-010',
            //     title: 'The Landscaper',
            //     medium: 'medium format color negative film',
            //     year: 2011,
            // },
            {
                path: 'persons-011',
                imagePath: 'persons-011',
                title: 'The Engineer',
                medium: 'medium format color negative film',
                year: 2011,
            },
        ]
    },
    {
        documentTitle: 'Spotless - Short Film by Rodrigo Barraza and Ewa Chruscicka',
        documentKeywords: 'spotless, vancouver, short film, video, rodrigo barraza, 16mm, film',
        documentDescription: 'xxx',
        videoControls: true,
        imagePath: 'spotless',
        title: 'Spotless',
        type: 'film',
        medium: '16mm black-and-white film',
        duration: '2 minutes, 59 seconds',
        year: 2012,
        path: 'spotless',
        description: 'In collaboration with <a href="https://ewachruscicka.ca/" target="_blank">Ewa Chruscicka</a>, Spotless is a 16mm short film shot in black-and-white stock. Ave Maria by Bach/Gounod in stereo sound.',
        orientation: 'horizontal',
        works: [
            {
                path: 'spotless',
                videoPath: 'spotless',
                title: 'Spotless',
                medium: '16mm black-and-white film',
                description: 'Spotless; 2minutes, 59seconds. A 16mm short film shot in black-and-white stock. Ave Maria by Bach/Gounod in stereo sound. In collaboration with <a href="https://ewachruscicka.ca/" target="_blank">Ewa Chruscicka.</a>',
                year: 2011,
            },
        ]
    },
    {
        documentTitle: 'TV Date - Music video by Rodrigo Barraza',
        documentKeywords: 'tv date, petroleum by-product, music video, rodrigo barraza, video',
        documentDescription: 'This music video was shot and produced for Vancouver-based band Petroleum By-Product.',
        videoControls: true,
        imagePath: 'tv-date',
        title: 'TV Date',
        type: 'film',
        medium: 'Digital video signal with stereo sound',
        duration: '3 minutes, 30 seconds',
        year: 2010,
        path: 'tv-date',
        ekphrasis: "Don't be disappointed in what you'll be seeing, I'm not very special, just a human being. You make me feel like I'm something quite outrageous. All I do is read the ads in yellow pages, and I'll sit all night all night by my TV screen.",
        description: 'This music video was shot and produced for <a href="https://www.youtube.com/user/PetroleumByProduct" target="_blank">Petroleum By-Product</a>, a Canadian new wave synth pop trio from Vancouver, BC. Directed and edited by <a href="https://davidedisaro.work/" target="_blank">Davide Di Saro</a>, produced by <a href="https://www.youtube.com/user/SallyDige" target="_blank">Sally Dige</a>, cinematography by <a href="https://ewachruscicka.ca/" target="_blank">Ewa Chruscicka</a>, videography by Rodrigo Barraza, <a href="https://www.linkedin.com/in/proryanbetts" target="_blank">Ryan Betts</a> and <a href="https://www.instagram.com/owen_ellis" target="_blank">Owen Ellis</a>.',
        works: [
            {
                path: 'tv-date',
                videoPath: 'tv-date',
                title: 'TV Date',
                description: 'An installation piece of 8-bit Super Mario. Composed of one hundred and fourty one 3½-inch floppy disks.',
                year: 2010,
            },
        ]
    },
    {
        documentTitle: 'Rip Apart - Music video by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        videoControls: true,
        orientation: 'horizontal',
        imagePath: 'rip-apart',
        path: 'rip-apart',
        title: 'Rip Apart',
        type: 'film',
        medium: 'Digital video signal with stereo sound',
        duration: '4 minutes, 51 seconds',
        year: 2011,
        ekphrasis: "Who cares for you?",
        description: 'This music video was shot and produced for <a href="https://www.youtube.com/user/PetroleumByProduct" target="_blank">Petroleum By-Product</a>, a Canadian new wave synth pop trio from Vancouver, BC. Directed and edited by <a href="https://www.instagram.com/kentweldon/" target="_blank">Katie Weldon</a>, produced by <a href="https://ewachruscicka.ca/" target="_blank">Ewa Chruscicka</a>, and videography by Rodrigo Barraza.',
        works: [
            {
                path: 'rip-apart',
                videoPath: 'rip-apart',
                title: 'Rip Apart',
                medium: 'Digital video signal with stereo sound',
                description: 'Spotless; 2minutes, 59seconds. A 16mm short film shot in black-and-white stock. Ave Maria by Bach/Gounod in stereo sound. In collaboration with <a href="https://ewachruscicka.ca/" target="_blank">Ewa Chruscicka.</a>',
                year: 2011,
            },
        ]
    },
    {
        documentTitle: 'Nature - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Nature',
        type: 'photography',
        medium: 'full-frame digital sensor and 35mm color reversal film',
        year: 2011,
        path: 'nature',
        works: [
            {
                path: '1N6A7045',
                imagePath: '1N6A7045',
                title: 'Over the Rainbow',
                medium: 'full-frame digital sensor',
                description: '',
                ekphrasis: 'Somewhere over the rainbow, bluebirds fly. And the dreams that you dare to dream really do come true.',
                year: 2010,
            },
            {
                path: 'nature-002',
                imagePath: 'nature-002',
                title: 'Orange Cone',
                medium: '35 mm color reversal film',
                description: '',
                year: 2010,
            },
            // {
            //     path: 'nature-003',
            //     imagePath: 'nature-003',
            //     title: 'Lightning',
            //     medium: 'full-frame digital sensor',
            //     description: '',
            //     year: 2010,
            // },
            // {
            //     path: 'nature-005',
            //     imagePath: 'nature-005',
            //     title: 'Rainbow No. 0001',
            //     medium: 'full-frame digital sensor',
            //     description: '',
            //     year: 2010,
            // },
            // {
            //     path: 'nature-006',
            //     imagePath: 'nature-006',
            //     title: 'Rainbow No. 0001',
            //     medium: 'full-frame digital sensor',
            //     description: '',
            //     year: 2010,
            // },
            {
                path: '_MG_9391',
                imagePath: '_MG_9391',
                title: 'Seagull',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '20090414_3266',
                imagePath: '20090414_3266',
                title: 'Blades',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
        ]
    },
    {
        documentTitle: 'xxx',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Urban',
        type: 'photography',
        medium: 'full-frame digital sensor',
        year: 2020,
        path: 'urban',
        works: [
            {
                path: 'urban-001',
                imagePath: 'urban-001',
                title: 'The Keefer',
                medium: 'full-frame digital sensor',
                description: 'Built in 2009, The Keefer is one of many projects aimed towards the gentrification of Chinatown and Downtown Eastside in Vancouver. Brought on by different causes and causing many effects, gentrification is the focus of many controversies in many cities around the globe.',
                year: 2021,
            },
            {
                path: 'Urban-002',
                imagePath: 'urban-002',
                title: 'Startup',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2018,
            },
            {
                path: 'urban-003',
                imagePath: 'urban-003',
                title: 'Stadium',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2019,
            },
            {
                path: 'urban-004',
                imagePath: 'urban-004',
                title: 'Vintage',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2021,
            },
            {
                path: 'urban-005',
                imagePath: 'urban-005',
                title: 'Santa María',
                medium: 'full-frame digital sensor',
                description: 'Taken outside the Parroquia Santa María Reina Parish in Lima, Peru. This landmark structure is a Roman Catholic church on the Ovalo Gutierrez in Miraflores.',
                year: 2017,
            },
            {
                path: 'urban-006',
                imagePath: 'urban-006',
                title: 'Bichon Frise',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '20091004_9999_55',
                imagePath: '20091004_9999_55',
                title: 'False Creek',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '_MG_2813',
                imagePath: '_MG_2813',
                title: 'Translink',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2007,
            },
            {
                path: '20090924_9999_1',
                imagePath: '20090924_9999_1',
                title: 'Pavement',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '20090905_9999_86 1',
                imagePath: '20090905_9999_86 1',
                title: 'Bricks and Windows',
                medium: 'full-frame digital sensor',
                description: "Taken by St. Paul's Hospital.",
                year: 2010,
            },
            {
                path: '2008-alley',
                imagePath: '2008-alley',
                title: 'The Back Alley',
                medium: '35 mm black-and-white film',
                description: "",
                year: 2018,
            },
        ],
    },
    {
        documentTitle: 'Ainimations - AI Art by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Ainimations',
        type: 'animation',
        medium: 'CLIP-guided diffusion, AI generated',
        year: 2022,
        path: 'ainimations',
        description: 'An collection of experimental artificial intelligence generated animations, which explore the motion capabilities of CLIP-guided diffusion.',
        videoControls: null,
        works: [
            {
                path: 'millhouse',
                videoPath: 'millhouse',
                title: 'Latent Skies No.1',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'black-hole',
                videoPath: 'black-hole',
                title: 'Black Hole',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'sparkles',
                videoPath: 'sparkles',
                title: 'Sparkles',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'clouds',
                title: 'Latent Skies No.2',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'breathing',
                title: 'Latent Skies No.3',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'bubbles',
                title: 'Latent Skies No.4',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'purple-rainbow',
                title: 'Latent Skies No.5',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'into-darkness',
                title: 'Latent Skies No.6',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: '7-seconds',
                title: 'Latent Skies No.13',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'breathing-diamonds',
                title: 'Latent Skies No.7',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'lightning',
                title: 'Latent Skies No.8',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'into-the-blue',
                title: 'Latent Skies No.9',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'orange-magenta',
                title: 'Latent Skies No.10',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'virgin',
                title: 'Latent Skies No.12',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'tropical',
                title: 'Latent Skies No.14',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'into-the-sand',
                title: 'Latent Skies No.15',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
            {
                path: 'millhouse',
                videoPath: 'through-the-cracks',
                title: 'Latent Skies No.11',
                year: 2022,
                medium: 'CLIP-guided diffusion, AI generated',
                duration: '15 seconds',
            },
        ]
    },
    {
        documentTitle: 'Super Mario - Installation by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        imagePath: '20448-mario',
        title: 'Super Mario',
        type: 'installation',
        medium: 'One hundred and fourty one 3½-inch colored floppy disks',
        year: 2007,
        path: '20448-mario',
        description: 'This installation piece features 8-bit Super Mario. Composed of one hundred and fourty one 3½-inch floppy disks, this piece makes up for a total of 204.48Mb.',
        works: [
            {
                path: '20448-mario',
                imagePath: '20448-mario',
                title: '204.48MB of Mario',
                medium: 'One hundred and fourty one 3½-inch colored floppy disks',
                description: 'An installation piece of 8-bit Super Mario. Composed of one hundred and fourty one 3½-inch floppy disks.',
                year: 2007,
            },
        ]
    },
    {
        documentTitle: 'Mollusca - AI Art by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Mollusca',
        type: 'ai',
        medium: 'CLIP-guided diffusion, AI generated',
        year: 2022,
        path: 'mollusca',
        works: [
            {
                path: 'mollusca-001',
                imagePath: 'mollusca-001',
                title: 'Mollusca No. 001',
                medium: 'CLIP-guided diffusion, AI generated',
                description: '',
                year: 2022,
            },
            {
                path: 'mollusca-002',
                imagePath: 'mollusca-002',
                title: 'Mollusca No. 002',
                medium: 'CLIP-guided diffusion, AI generated',
                description: '',
                year: 2022,
            },
            {
                path: 'mollusca-003',
                imagePath: 'mollusca-003',
                title: 'Mollusca No. 003',
                medium: 'CLIP-guided diffusion, AI generated',
                description: '',
                year: 2022,
            },
        ]
    },
    {
        documentTitle: 'Lollipop - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Lollipop',
        type: 'photography',
        medium: 'medium format color reversal film',
        year: 2010,
        path: 'lollipop',
        works: [
            {
                path: '2010-120-fuji-velvia-earths-01',
                imagePath: '2010-120-fuji-velvia-earths-01',
                title: 'Vanilla',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
            {
                path: '2010-120-fuji-velvia-earths-02',
                imagePath: '2010-120-fuji-velvia-earths-02',
                title: 'Strawberry',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
            {
                path: '2010-120-fuji-velvia-earths-03',
                imagePath: '2010-120-fuji-velvia-earths-03',
                title: 'Blue Raspberry',
                medium: 'medium format color reversal film',
                description: '',
                year: 2010,
            },
        ]
    },
    {
        documentTitle: 'Aura of Home - Photography by Rodrigo Barraza and Adam Johannesson',
        documentKeywords: 'aura of home, vancouver, photography, rodrigo barraza, adam johannesson, home, film',
        documentDescription: 'A series of film photographs, touching on the notion of what it means to be at home. In collaboration with Adam Johannesson.',
        title: 'Aura of Home',
        orientation: 'square',
        type: 'photography',
        medium: 'medium format color negative film',
        year: 2010,
        path: 'aura-of-home',
        ekphrasis: "Waking up in the morning is the hardest part about losing someone. Something about sleep convinces you that you'll wake up with a fresh start, but every morning I wake up, and remember you're gone.",
        description: 'The Aura of Home is a series of medium format color negative film series, touching on the notions and ideas of what it means to be at home. In collaboration with <a href="https://www.instagram.com/audioappalled/" target="_blank">Adam Johannesson</a>.',
        works: [
            {
                path: 'aura-of-home-001',
                imagePath: 'aura-of-home-001',
                title: 'Tom',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
            {
                path: 'aura-of-home-002',
                imagePath: 'aura-of-home-002',
                title: 'Chaya',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
            {
                path: 'aura-of-home-003',
                imagePath: 'aura-of-home-003',
                title: 'Dexter',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
            {
                path: 'aura-of-home-004',
                imagePath: 'aura-of-home-004',
                title: 'Mariana & Makayla',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
            {
                path: 'aura-of-home-005',
                imagePath: 'aura-of-home-005',
                title: 'Matt',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
        ]
    },
    {
        documentTitle: 'Portraiture - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Portraiture',
        type: 'photography',
        medium: 'medium format film photography',
        year: 'Ongoing',
        path: 'portraiture',
        works: [
            {
                path: 'fashion-001',
                imagePath: 'fashion-001',
                title: 'FINE',
                medium: 'medium format film photography',
                ekphrasis: "Fine, fine. Everywhere that I go, fine fine. I'm the one in control, fine, fine.",
                description: "A quick shoot, out by East Vancouver, for <a href='https://www.instagram.com/osmoses/' target='_blank'>Buni Kor</a>'s FINE, featuring <a href='https://www.instagram.com/the.goldkid/' target='_blank'>Gold Kid</a>. <button-component></button-component>",
                year: 2021,
                filename: '1N6A6510',
            },
            {
                path: '_MG_0004',
                imagePath: '_MG_0004',
                title: 'Book of Kings',
                medium: 'full-frame digital sensor',
                ekphrasis: "A young man is freed from his father's tyranny by a mysterious figure, only to find himself with a horrible curse.",
                description: "A photograph of Cameron Crosby and Tomislav Pejic in Ali Hasan's film, The Book of Kings, 2011.",
                year: 2011,
            },
            {
                path: 'fashion-002',
                imagePath: 'fashion-002',
                title: 'Hatch Door',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-003',
                imagePath: 'fashion-003',
                title: 'Cultivating Mass',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: '_MG_5526',
                imagePath: '_MG_5526',
                title: 'Pink Bricks',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2015,
            },
            {
                path: 'fashion-005',
                imagePath: 'fashion-005',
                title: 'Red Wires',
                medium: 'medium format film photography',
                description: 'Kleenz',
                year: 2010,
            },
            // {
            //     path: 'fashion-006',
            //     imagePath: 'fashion-006',
            //     title: 'Weeping Tree',
            //     medium: 'medium format film photography',
            //     description: '',
            //     year: 2010,
            // },
            {
                path: 'fashion-007',
                imagePath: 'fashion-007',
                title: 'Weeping Shrub',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-010',
                imagePath: 'fashion-010',
                title: 'Beret and Beer',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-004',
                imagePath: 'fashion-004',
                title: 'Listen',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-008',
                imagePath: 'fashion-008',
                title: '7up',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-009',
                imagePath: 'fashion-009',
                title: 'Slide Up',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-011',
                imagePath: 'fashion-011',
                title: 'Checkered Hearts',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-012',
                imagePath: 'fashion-012',
                title: 'Spring Hike',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'fashion-013',
                imagePath: 'fashion-013',
                title: 'Happy Couple No. 1',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: '20080829_0920',
                imagePath: '20080829_0920',
                title: 'Happy Couple No. 2',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: 'IMG_9847',
                imagePath: 'IMG_9847',
                title: 'Amar No.1',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2011,
            },
            {
                path: 'IMG_9830',
                imagePath: 'IMG_9830',
                title: 'Amar No.2',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2011,
            },
            // {
            //     path: '_MG_9623',
            //     imagePath: '_MG_9623',
            //     title: 'Damask Violet',
            //     medium: 'full-frame digital sensor',
            //     description: '',
            //     year: 2015,
            // },
            // {
            //     path: '1N6A4983',
            //     imagePath: '1N6A4983',
            //     title: 'Viaducts',
            //     medium: 'full-frame digital sensor',
            //     description: '',
            //     year: 2019,
            // },
            {
                path: '1N6A3852',
                imagePath: '1N6A3852',
                title: 'Jean Paul',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2018,
            },
            {
                path: '1N6A2690',
                imagePath: '1N6A2690',
                title: 'Jesse',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            // {
            //     path: 'rodrigoBarraza_1289',
            //     imagePath: 'rodrigoBarraza_1289',
            //     title: 'Blue and Pink',
            //     medium: 'full-frame digital sensor',
            //     description: '',
            //     year: 2008,
            // },
        ]
    },
    {
        documentTitle: 'Cities - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Cities',
        type: 'photography',
        medium: 'photography',
        year: 2010,
        path: 'cities',
        orientation: 'horizontal',
        works: [
            {
                path: 'cities-san-francisco',
                imagePath: 'cities-san-francisco',
                title: 'San Francisco',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'cities-vancouver',
                imagePath: 'cities-vancouver',
                title: 'Vancouver',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'cities-los-angeles',
                imagePath: 'cities-los-angeles',
                title: 'Los Angeles',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'cities-calango',
                imagePath: 'cities-calango',
                title: 'Calango',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'cities-burnaby',
                imagePath: 'cities-burnaby',
                title: 'Burnaby',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
            {
                path: 'cities-lima',
                imagePath: 'cities-lima',
                title: 'Lima',
                medium: 'medium format film photography',
                description: '',
                year: 2010,
            },
        ]
    },
    {
        documentTitle: 'Aerial - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Aerial',
        type: 'photography',
        medium: 'full-frame digital sensor',
        year: '2017-2020',
        path: 'aerial',
        works: [
            {
                path: 'aerial-1N6A0097',
                imagePath: 'aerial-1N6A0097',
                title: 'Aerial No. 001',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2018,
            },
            {
                path: 'aerial-1N6A0104',
                imagePath: 'aerial-1N6A0104',
                title: 'Aerial No. 002',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2020,
            },
            {
                path: 'aerial-1N6A0110',
                imagePath: 'aerial-1N6A0110',
                title: 'Aerial No. 003',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2019,
            },
            {
                path: 'aerial-1N6A1737',
                imagePath: 'aerial-1N6A1737',
                title: 'Aerial No. 004',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2017,
            },
        ],
    },
    {
        documentTitle: 'Layers - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Layers',
        type: 'photography',
        medium: 'full-frame digital sensor',
        year: 2017,
        path: 'layers',
        works: [
            {
                path: 'rodrigo-barraza-layers-five-red-doors',
                imagePath: 'rodrigo-barraza-layers-five-red-doors',
                title: 'Five Red Doors',
                orientation: 'horizontal',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2017,
                filename: '1N6A8918',
            },
            {
                path: '1N6A8967',
                imagePath: '1N6A8967',
                title: 'Seven Trees',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2017,
                filename: '1N6A8605',
            },
            {
                path: 'rodrigo-barraza-layers-ten-cactus',
                imagePath: 'rodrigo-barraza-layers-ten-cactus',
                title: 'Ten Cactus',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2017,
                filename: '1N6A0548',
            },
            {
                path: 'rodrigo-barraza-layers-nine-shores',
                imagePath: 'rodrigo-barraza-layers-nine-shores',
                title: 'Nine Shores',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2017,
                filename: '1N6A6809',
            },
        ],
    },
    {
        documentTitle: 'Artifacts - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Artifacts',
        type: 'photography',
        medium: 'photography',
        year: 2020,
        path: 'artifacts',
        works: [
            {
                path: '1N6A6964',
                imagePath: '1N6A6964',
                title: 'WE ARE OPEN',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '_MG_9869',
                imagePath: '_MG_9869',
                title: 'Blue, Red and White',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '1N6A4346',
                imagePath: '1N6A4346',
                title: 'Lantern',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '1N6A4354',
                imagePath: '1N6A4354',
                title: 'Door',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '20090905_9999_12',
                imagePath: '20090905_9999_12',
                title: 'Seven',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '_MG_6915',
                imagePath: '_MG_6915',
                title: 'Totem',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '_MG_6982',
                imagePath: '_MG_6982',
                title: 'Sink',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '20090906_9999_461',
                imagePath: '20090906_9999_461',
                title: 'Haro Street 1500',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: 'watertower',
                imagePath: 'watertower',
                title: 'Watertower',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '20090503_4346',
                imagePath: '20090503_4346',
                title: 'Nine',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: '_MG_9924',
                imagePath: '_MG_9924',
                title: 'Someone',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
            {
                path: 'IMG_0396',
                imagePath: 'IMG_0396',
                title: 'GREEN',
                medium: 'full-frame digital sensor',
                description: '',
                year: 2010,
            },
        ],
    },
    {
        documentTitle: 'Slashed - Photography by Rodrigo Barraza',
        documentKeywords: 'xxx',
        documentDescription: 'xxx',
        title: 'Slashed',
        type: 'photography',
        medium: 'medium format color negative film',
        year: 2010,
        path: 'slashed',
        orientation: 'square',
        ekphrasis: "We don't make mistakes—we have happy accidents.",
        description: '',
        works: [
            {
                path: '2010-120-fuji-pro-160s-mr-wang',
                imagePath: '2010-120-fuji-pro-160s-mr-wang',
                title: 'Mr. Wang',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
            {
                path: '2010-120-fuji-pro-160s-arabians',
                imagePath: '2010-120-fuji-pro-160s-arabians',
                title: 'Arabian Brothers',
                medium: 'medium format color negative film',
                description: '',
                year: 2010,
            },
            {
                path: '2010-120-fuji-pro-160s-business',
                imagePath: '2010-120-fuji-pro-160s-business',
                title: 'The Business Man',
                medium: 'medium format color negative film',
                year: 2010,
                ekphrasis: 'If I see this online, I will sue you!'
            },
            {
                path: '2010-120-fuji-pro-160s-old-lady',
                imagePath: '2010-120-fuji-pro-160s-old-lady',
                title: 'Beth',
                medium: 'medium format color negative film',
                year: 2010,
            },
            {
                path: '2010-120-fuji-pro-160s-construction-2',
                imagePath: '2010-120-fuji-pro-160s-construction-2',
                title: 'Sanitation Worker',
                medium: 'medium format color negative film',
                year: 2010
            },
            {
                path: '2010-120-fuji-pro-160s-manager-1',
                imagePath: '2010-120-fuji-pro-160s-manager-1',
                title: 'Landlord',
                medium: 'medium format color negative film',
                year: 2010,
            },
            {
                path: '2010-120-fuji-pro-160s-south-african-couple',
                imagePath: '2010-120-fuji-pro-160s-south-african-couple',
                title: 'The Couple',
                medium: 'medium format color negative film',
                year: 2010,
                ekphrasis: "... of course, we're just visiting from South Africa.",
            },
            {
                path: '2010-120-fuji-pro-160s-tree-cutter',
                imagePath: '2010-120-fuji-pro-160s-tree-cutter',
                title: 'Landscaper',
                medium: 'medium format color negative film',
                year: 2010,
            },
            {
                path: '2010-120-fuji-pro-160s-powerline-worker',
                imagePath: '2010-120-fuji-pro-160s-powerline-worker',
                title: 'Lineworker',
                medium: 'medium format color negative film',
                year: 2010,
            },
        ]
    },
];

export default ArtCollectionsCollection;
  