const ArtCollectionsCollection = [
    // {
    //     imagePath: 'dreamworks',
    //     name: 'Dreamworks',
    //     medium: 'medium format slide film',
    //     year: 2011,
    //     path: 'dreamworks',
    //     description: 'Dreamwork; images regarding the intangibility of memories, emotions, dreams and previous events in life. Memory alters, emotions change, places shift, and locations are never the same.',
    //     keywords: 'rodrigo, barraza, film, photography, dream, memory, childhood, medium format, hasselblad, darkroom, analog, multiple exposure, slide, traditional, fine art, film, dreamworks',
    //     works: [
    //         {
    //             path: 'dreamworks-001',
    //             imagePath: 'dreamworks-001',
    //             name: 'Dreamworks №001',
    //             medium: 'Medium format slide film',
    //             description: 'Amalgamated memories of the beach, from a time that might have never happened. A feeling of jamais vu.',
    //             year: 2010,
    //         },
    //     ]
    // },
    {
        imagePath: 'tardigrades',
        name: 'Tardigrades',
        type: 'ai',
        medium: 'AI generated art',
        year: 2022,
        path: 'tardigrades',
        description: 'Tardigrade is a series of aritificial intelligence generated images of animals in the phylum Tardigrada.',
        keywords: 'ai art, artificial intelligence, machine learning, tardigrade, tardigrada',
        works: [
            {
                path: 'tardigrade-001',
                imagePath: 'tardigrade-001',
                name: 'Diamond Tardigrade №001',
                medium: 'AI generated, CLIP-guided diffusion',
                description: 'The Diamond Tardigrade is a species that has a single large eye and carries around a home made out of transparent diamonds. They are found in a variety of habitats, but prefer to live in moist environments. Vitrum tardigradum are able to live for long periods of time without food or water, and can even withstand being frozen or boiled. When they do need to drink, they absorb water through their bodies.',
                year: 'August 2022',
            },
            {
                path: 'tardigrade-002',
                imagePath: 'tardigrade-002',
                name: 'Pink Velvet Tardigrade №001',
                medium: 'AI generated, CLIP-guided diffusion',
                description: '',
                year: 'August 2022',
            },
            {
                path: 'tardigrade-003',
                imagePath: 'tardigrade-003',
                name: 'Carbon Black Tardigrade №001',
                medium: 'AI generated, CLIP-guided diffusion',
                year: 'August 2022',
            },
            {
                path: 'tardigrade-004',
                imagePath: 'tardigrade-004',
                name: 'Astrophysical Tardigrade №001',
                medium: 'AI generated, CLIP-guided diffusion',
                year: 'August 2022',
            },
            {
                path: 'tardigrade-005',
                imagePath: 'tardigrade-005',
                name: 'Anodic Tardigrade №001',
                medium: 'AI generated, CLIP-guided diffusion',
                year: 'August 2022',
            },
            {
                path: 'tardigrade-006',
                imagePath: 'tardigrade-006',
                name: 'Anodic Tardigrade №002',
                medium: 'AI generated, CLIP-guided diffusion',
                year: 'August 2022',
            },
        ]
    },
    {
        imagePath: 'dreamworks',
        name: 'Dreamworks',
        type: 'photography',
        medium: 'medium format slide film',
        year: 2011,
        path: 'dreamworks',
        ekphrasis: 'Dreamworks; memories, emotions, dreams, and their intangibility. Memories develop as information is encoded, stored and retried. Emotions are brought on through assossiations. Dreams are a succession of concepts occuring involuntarily in the mind curing certain stages of sleep.',
        description: 'This collection of multiple exposure photographs shot on medium format slide film, is a visual exploration on the fragility of memories, emotional responses, experience of dreams, and the intertwinedness these three topics share.',
        keywords: 'rodrigo, barraza, film, photography, dream, memory, childhood, medium format, hasselblad, darkroom, analog, multiple exposure, slide, traditional, fine art, film, dreamworks',
        works: [
            {
                path: 'dreamworks-001',
                imagePath: 'dreamworks-001',
                name: 'The Beach',
                medium: 'Medium format slide film',
                description: 'Amalgamated memories of the beach, from a time that might have never happened. A feeling of jamais vu.',
                year: 2010,
            },
            {
                path: 'dreamworks-002',
                imagePath: 'dreamworks-002',
                name: 'The Yard',
                medium: 'Medium format slide film',
                description: 'Seven very similar looking corners of a fenced-out backyard. A feeling of déjà vu.',
                year: 2010,
            },
            {
                path: 'dreamworks-003',
                imagePath: 'dreamworks-003',
                name: 'The Park',
                medium: 'Medium format slide film',
                description: 'When one is so tired that far away objects feel close while nearby objects can be seen distance away. Like vertigo that goes sideways.',
                year: 2011,
            },
            {
                path: 'dreamworks-004',
                imagePath: 'dreamworks-004',
                name: 'Dreamworks №004',
                medium: 'Medium format slide film',
                description: 'When one is so tired that far away objects feel close while nearby objects can be seen distance away. Like vertigo that goes sideways.',
                year: 2011,
            },
        ]
    },
    {
        imagePath: 'cops',
        name: 'Cops',
        type: 'photography',
        medium: '35mm black and white film',
        year: 2010,
        path: 'cops',
        description: '',
        works: [
            {
                path: 'cops-001',
                imagePath: 'cops-001',
                name: 'Serve',
                medium: '35 mm black and white film',
                description: '',
                year: 2010,
            },
            {
                path: 'cops-002',
                imagePath: 'cops-002',
                name: 'Protect',
                medium: '35 mm black and white film',
                description: '',
                year: 2010,
            },
            {
                path: 'cops-003',
                imagePath: 'cops-003',
                name: 'Justice',
                medium: '35 mm black and white film',
                description: '',
                year: 2010,
            },
        ]
    },
    {
        imagePath: 'persons',
        name: 'Persons',
        type: 'photography',
        medium: '120 medium format color negative film',
        year: 2010,
        path: 'persons',
        works: [
            {
                path: 'persons-001',
                imagePath: 'persons-001',
                name: 'The Model',
                medium: '120 medium format color negative film',
                description: '',
                year: 0,
            },
            {
                path: 'persons-002',
                imagePath: 'persons-002',
                name: 'The Writer',
                medium: '120 medium format color negative film',
                description: '',
                year: 0,
            },
            {
                path: 'persons-003',
                imagePath: 'persons-003',
                name: 'The Art Teacher',
                medium: '120 medium format color negative film',
                year: 0,
            },
            {
                path: 'persons-004',
                imagePath: 'persons-004',
                name: 'The Landlord',
                medium: '120 medium format color negative film',
                year: 0,
            },
            {
                path: 'persons-005',
                imagePath: 'persons-005',
                name: 'The Lawer',
                medium: '120 medium format color negative film',
                year: 0,
                description: '"If I see this online, I will sue you"'
            },
            {
                path: 'persons-006',
                imagePath: 'persons-006',
                name: 'The Vagabonds',
                medium: '120 medium format color negative film',
                year: 0,
            },
            {
                path: 'persons-007',
                imagePath: 'persons-007',
                name: 'The Actor',
                medium: '120 medium format color negative film',
                year: 0,
            },
            {
                path: 'persons-008',
                imagePath: 'persons-008',
                name: 'The Courier',
                medium: '120 medium format color negative film',
                year: 0,
            },
            {
                path: 'persons-009',
                imagePath: 'persons-009',
                name: 'The Clerk',
                medium: '120 medium format color negative film',
                year: 0,
            },
            {
                path: 'persons-010',
                imagePath: 'persons-010',
                name: 'The Landscaper',
                medium: '120 medium format color negative film',
                year: 0,
            },
            {
                path: 'persons-011',
                imagePath: 'persons-011',
                name: 'The Engineer',
                medium: '120 medium format color negative film',
                year: 0,
            },
        ]
    },
    {
        imagePath: 'walks',
        name: 'Walks',
        type: 'photography',
        medium: 'photography',
        year: 2022,
        path: 'walks',
        ekphrasis: 'There is a certain feeling that comes on when walking around with a camera. It is a lonely but comfortable warmth.',
        description: 'This is a collection of photographs shot on black and white medium format slide film.',
        works: [
            {
                path: 'walks-001',
                imagePath: 'walks-001',
                name: 'Shower',
                medium: '120 black and white film',
                description: 'Overlooking the container ships, breakbulk carriers and tankers from English Bay, Vancouver.',
                year: 2009,
            },
            {
                path: 'walks-002',
                imagePath: 'walks-002',
                name: 'Beams',
                medium: '120 black and white film',
                description: 'Testing the spotlights at Sunset Beach for the upcoming 2010 Vancouver Olympics.',
                year: 2010,
            },
            {
                path: 'walks-003',
                imagePath: 'walks-003',
                name: 'We',
                medium: '120 black and white film',
                description: 'WE, One of Jaume Plensa’s beautiful sculptures, 2008.',
                year: 2008,
            },
            {
                path: 'walks-004',
                imagePath: 'walks-004',
                name: 'Robson and Granville',
                medium: '120 black and white film',
                description: 'A little over two weeks of chaos, as everyone begins to flood the streets in preperation for the 2010 Winter Olympics in Vancouver.',
                year: 2010,
            },
            {
                path: 'walks-005',
                imagePath: 'walks-005',
                name: 'Dirty, Dangerous and Demeaning',
                medium: '120 black and white film',
                description: 'Also known as the 3Ds; Dirty, Dangerous and Demanding is a North American neologism derived from the Japanese expression: kitanai, kiken, kitsui[1] (汚い "dirty", 危険 "dangerous", きつい "demanding"), and refers to certain kinds of labor often performed by unionized blue-collar workers.',
                year: 0,
            },
        ]
    },
    {
        imagePath: 'crystal-landscapes',
        name: 'Crystal Landscapes',
        type: 'ai',
        medium: 'AI generated, CLIP-guided diffusion',
        year: 'Ongoing',
        path: 'crystal-landscapes',
        description: 'A collection of experimentations.',
        works: [
            {
                path: 'crystal-skies-001',
                imagePath: 'crystal-skies-001',
                name: 'Crystal Skies №001',
                medium: 'AI generated, CLIP-guided diffusion',
                year: 2022,
            },
            {
                path: 'crystal-beach-001',
                imagePath: 'crystal-beach-001',
                name: 'Crystal Beach №001',
                medium: 'AI generated, CLIP-guided diffusion',
                description: '',
                year: 2022,
            },
            {
                path: 'crystal-beach-002',
                imagePath: 'crystal-beach-002',
                name: 'Crystal Beach №002',
                medium: 'AI generated, CLIP-guided diffusion',
                description: '',
                year: 2022,
            },
            // {
            //     path: 'crystal-landscapes-004',
            //     imagePath: 'crystal-landscapes-004',
            //     name: 'Crystal Beach №002',
            //     medium: 'AI generated, CLIP-guided diffusion',
            //     year: 2022,
            // },
            // {
            //     path: 'crystal-peak-001',
            //     imagePath: 'crystal-peak-001',
            //     name: 'Crystal Peak №002',
            //     medium: 'AI generated, CLIP-guided diffusion',
            //     year: 2022,
            // },
            {
                path: 'crystal-ridge-001',
                imagePath: 'crystal-ridge-001',
                name: 'Crystal Ridge №002',
                medium: 'AI generated, CLIP-guided diffusion',
                year: 2022,
            },
            {
                path: 'crystal-seashore-001',
                imagePath: 'crystal-seashore-001',
                name: 'Crystal Seashore №002',
                medium: 'AI generated, CLIP-guided diffusion',
                year: 2022,
            },
            // {
            //     path: 'crystal-city-001',
            //     imagePath: 'crystal-city-001',
            //     name: 'Crystal City №001',
            //     medium: 'AI generated, CLIP-guided diffusion',
            //     year: 2022,
            // },
        ]
    },
    {
        imagePath: 'ink',
        name: 'Ink',
        type: 'photography',
        medium: 'mixed media',
        year: 2022,
        path: 'tardigrades',
    },
    {
        imagePath: 'spotless',
        name: 'Spotless',
        type: 'video',
        medium: '2 minutes 59 seconds. 16mm black and white film',
        year: 2012,
        path: 'spotless',
        description: 'In collaboration with <a href="http://ewachruscicka.ca" target="_blank">Ewa Chruscicka</a>, Spotless is a 16mm short film shot in black and white stock. Ave Maria by Bach/Gounod in stereo sound.',
        works: [
            {
                path: 'spotless',
                videoPath: 'spotless',
                name: 'Spotless',
                medium: '16mm black and white film',
                description: 'Spotless; 2minutes, 59seconds. A 16mm short film shot in black and white stock. Ave Maria by Bach/Gounod in stereo sound. In collaboration with <a href="http://ewachruscicka.ca" target="_blank">Ewa Chruscicka.</a>',
                year: 2011,
            },
        ]
    },
    {
        imagePath: 'manufactured-portraits',
        name: 'Manufactured Portraits',
        type: 'ai',
        medium: 'generative art',
        year: 2022,
        path: 'tardigrades',
    },
    {
        imagePath: 'nature',
        name: 'Nature',
        type: 'photography',
        medium: 'photography',
        year: 2011,
        path: 'nature',
        works: [
            {
                path: 'nature-001',
                imagePath: 'nature-001',
                name: 'Rainbow',
                medium: '35mm slide film',
                description: '',
                year: '2010',
            },
            {
                path: 'nature-002',
                imagePath: 'nature-002',
                name: 'The Orange Cone',
                medium: '35mm slide film',
                description: '',
                year: '2010',
            },
            {
                path: 'nature-003',
                imagePath: 'nature-003',
                name: 'Lightning',
                medium: '35mm slide film',
                description: '',
                year: '2010',
            },
            {
                path: 'nature-005',
                imagePath: 'nature-005',
                name: 'Rainbow №0001',
                medium: '35mm slide film',
                description: '',
                year: '2010',
            },
            {
                path: 'nature-006',
                imagePath: 'nature-006',
                name: 'Rainbow №0001',
                medium: '35mm slide film',
                description: '',
                year: '2010',
            },
        ]
    },
    {
        imagePath: 'shorelines',
        name: 'Shorelines',
        type: 'photography',
        medium: 'Digital photography',
        year: 2020,
        path: 'shorelines',
        works: [
            {
                path: 'shorelines-001',
                imagePath: 'shorelines-001',
                name: 'Shorelines №001',
                medium: 'Digital photography. Multiple Exposures.',
                description: '',
                year: '2010',
            },
            {
                path: 'shorelines-002',
                imagePath: 'shorelines-002',
                name: 'Shorelines №002',
                medium: 'Digital photography. Multiple Exposures.',
                description: '',
                year: '2010',
            },
            {
                path: 'shorelines-003',
                imagePath: 'shorelines-003',
                name: 'Shorelines №003',
                medium: 'Digital photography. Multiple Exposures.',
                description: '',
                year: '2010',
            },
        ],
    },
    {
        imagePath: 'urban',
        name: 'Urban',
        type: 'photography',
        medium: 'Digital photography',
        year: 2020,
        path: 'urban',
        works: [
            {
                path: 'urban-001',
                imagePath: 'urban-001',
                name: 'The Keefer',
                medium: 'full-frame 35 mm digital sensor',
                description: 'Built in 2009, The Keefer is one of many projects aimed towards the gentrification of Chinatown and Downtown Eastside in Vancouver. Brought on by different causes and causing many effects, gentrification is the focus of many controversies in many cities around the globe.',
                year: '2021',
            },
            {
                path: 'Urban-002',
                imagePath: 'urban-002',
                name: 'Startup',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2018',
            },
            {
                path: 'urban-003',
                imagePath: 'urban-003',
                name: 'Stadium',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2019',
            },
            {
                path: 'urban-004',
                imagePath: 'urban-004',
                name: 'Vintage',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2021',
            },
            {
                path: 'urban-005',
                imagePath: 'urban-005',
                name: 'Santa María',
                medium: 'full-frame 35 mm digital sensor',
                description: 'Taken outside the Parroquia Santa María Reina Parish in Lima, Peru. This landmark structure is a Roman Catholic church on the Ovalo Gutierrez in Miraflores.',
                year: '2017',
            },
            {
                path: 'urban-006',
                imagePath: 'urban-006',
                name: 'Urban №006',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2010',
            },
        ],
    },
    {
        imagePath: 'tv-date',
        name: 'Petroleum By-Product: TV Date',
        type: 'video',
        medium: '3 minutes, 30 seconds. Digital video',
        year: 2010,
        path: 'tv-date',
        description: 'TV Date; 3minutes, 30seconds. Digital video signal with stereo sound. A music video shot in high definition for local Vancouver band Petroleum By-Product. In collaboration with Director Davide Di Saro, Cinematographer Ewa Chruscicka, and Videographer Owen Ellis.',
        works: [
            {
                path: 'tv-date',
                videoPath: 'tv-date',
                name: 'TV Date',
                year: 2010,
            },
        ]
    },
    {
        imagePath: '20448-mario',
        name: '204.48MB of Mario',
        type: 'installation',
        medium: 'Installation, 141 3½-inch floppy disks',
        year: 2007,
        path: '20448-mario',
        description: 'A reinterpretation of NES-era Mario. Created with 141 3½-inch floppy disks.',
        works: [
            {
                path: '20448-mario',
                imagePath: '20448-mario',
                name: '204.48MB of Mario',
                medium: 'Installation, 141 3½-inch floppy disks',
                description: '',
                year: 'Oct. 2007',
            },
        ]
    },
    {
        imagePath: 'mollusca',
        name: 'Mollusca',
        type: 'photography',
        medium: 'AI generated art',
        year: 2022,
        path: 'mollusca',
        works: [
            {
                path: 'mollusca-001',
                imagePath: 'mollusca-001',
                name: 'Mollusca №001',
                medium: 'AI generated, CLIP-guided diffusion',
                description: '',
                year: 'Oct. 2007',
            },
            {
                path: 'mollusca-002',
                imagePath: 'mollusca-002',
                name: 'Mollusca №002',
                medium: 'AI generated, CLIP-guided diffusion',
                description: '',
                year: 'Oct. 2007',
            },
            {
                path: 'mollusca-003',
                imagePath: 'mollusca-003',
                name: 'Mollusca №003',
                medium: 'AI generated, CLIP-guided diffusion',
                description: '',
                year: 'Oct. 2007',
            },
        ]
    },
    {
        imagePath: 'aura-of-home',
        name: 'The Aura of Home',
        type: 'photography',
        medium: 'medium format film photography',
        year: 2010,
        path: 'the-aura-of-home',
        description: 'The Aura of Home; An on going photographic series, touching on the notions and ideas of what it means to be at home. In collaboration with <a href="https://www.linkedin.com/in/adam-johannesson-9638b880" target="_blank">Adam Johannesson</a>.',
        works: [
            {
                path: 'aura-of-home-001',
                imagePath: 'aura-of-home-001',
                name: 'The Aura of Home: Greg',
                medium: 'medium format 120 color film',
                description: '',
                year: '2010',
            },
            {
                path: 'aura-of-home-002',
                imagePath: 'aura-of-home-002',
                name: 'The Aura of Home: Kayla',
                medium: 'medium format 120 color film',
                description: '',
                year: '2010',
            },
            {
                path: 'aura-of-home-003',
                imagePath: 'aura-of-home-003',
                name: 'The Aura of Home: Dexter',
                medium: 'medium format 120 color film',
                description: '',
                year: '2010',
            },
            {
                path: 'aura-of-home-004',
                imagePath: 'aura-of-home-004',
                name: 'The Aura of Home: Mariana',
                medium: 'medium format 120 color film',
                description: '',
                year: '2010',
            },
        ]
    },
    {
        imagePath: 'fashion',
        name: 'Fashion',
        type: 'photography',
        medium: 'medium format film photography',
        year: 2010,
        path: 'fashion',
        works: [
            {
                path: 'fashion-001',
                imagePath: 'fashion-001',
                name: 'Luis',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-002',
                imagePath: 'fashion-002',
                name: 'Sarah',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-003',
                imagePath: 'fashion-003',
                name: 'Mike',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-004',
                imagePath: 'fashion-004',
                name: 'Ewa',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-005',
                imagePath: 'fashion-005',
                name: 'Kleenz',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-006',
                imagePath: 'fashion-006',
                name: 'Geelda №001',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-007',
                imagePath: 'fashion-007',
                name: 'Geelda №002',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-008',
                imagePath: 'fashion-008',
                name: 'Sina',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-009',
                imagePath: 'fashion-009',
                name: 'Jensa',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-010',
                imagePath: 'fashion-010',
                name: 'Nader',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-011',
                imagePath: 'fashion-011',
                name: 'Lorisa',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-012',
                imagePath: 'fashion-012',
                name: 'Gerard & Ewa',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'fashion-013',
                imagePath: 'fashion-013',
                name: 'The Aura of Home №013',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
        ]
    },
    {
        imagePath: 'cities',
        name: 'Cities',
        type: 'photography',
        medium: 'digital photography',
        year: 2010,
        path: 'cities',
        works: [
            {
                path: 'cities-san-francisco',
                imagePath: 'cities-san-francisco',
                name: 'Cities: San Francisco',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'cities-vancouver',
                imagePath: 'cities-vancouver',
                name: 'Cities: Vancouver',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'cities-los-angeles',
                imagePath: 'cities-los-angeles',
                name: 'Cities: Los Angeles',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'cities-calango',
                imagePath: 'cities-calango',
                name: 'Cities: Calango',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'cities-burnaby',
                imagePath: 'cities-burnaby',
                name: 'Cities: Burnaby',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
            {
                path: 'cities-lima',
                imagePath: 'cities-lima',
                name: 'Cities: Lima',
                medium: 'medium format film photography',
                description: '',
                year: '2010',
            },
        ]
    },
    {
        imagePath: 'aerial',
        name: 'Aerial',
        type: 'photography',
        medium: 'digital photography',
        year: 2020,
        path: 'aerial',
        works: [
            {
                path: 'aerial-1N6A0097',
                imagePath: 'aerial-1N6A0097',
                name: 'Aerial №001',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2010',
            },
            {
                path: 'aerial-1N6A0104',
                imagePath: 'aerial-1N6A0104',
                name: 'Aerial №002',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2010',
            },
            {
                path: 'aerial-1N6A0110',
                imagePath: 'aerial-1N6A0110',
                name: 'Aerial №003',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2010',
            },
            {
                path: 'aerial-1N6A1737',
                imagePath: 'aerial-1N6A1737',
                name: 'Aerial №004',
                medium: 'full-frame 35 mm digital sensor',
                description: '',
                year: '2010',
            },
        ],
    },
];
  export default ArtCollectionsCollection;
  